apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: birdeye-addons
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: grafana
            path: tf-wi-aws/eks-cluster-components/charts/grafana
            valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/grafana.yaml
            namespace: monitoring

          # - name: ingress-nginx
          #   path: tf-wi-aws/eks-cluster-components/charts/ingress-nginx
          #   valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/ingress-nginx.yaml
          #   namespace: ingress-nginx

          - name: keda
            path: tf-wi-aws/eks-cluster-components/charts/keda
            valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/keda.yaml
            namespace: keda

          - name: loki
            path: tf-wi-aws/eks-cluster-components/charts/loki
            valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/loki.yaml
            namespace: loki

          - name: prometheus
            path: tf-wi-aws/eks-cluster-components/charts/prometheus
            valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/prometheus.yaml
            namespace: monitoring

          - name: statsd-exporter
            path: tf-wi-aws/eks-cluster-components/charts/statsd-exporter
            valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/statsd-exporter.yaml
            namespace: monitoring

          - name: tempo
            path: tf-wi-aws/eks-cluster-components/charts/tempo
            valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/tempo.yaml
            namespace: tempo

          # - name: kubecost
          #   path: tf-wi-aws/eks-cluster-components/charts/kubecost
          #   valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/kubecost.yaml
          #   namespace: kubecost

          # - name: aws-load-balancer-controller
          #   path: tf-wi-aws/eks-cluster-components/charts/aws-alb-controller
          #   valueFile: environments/stage-001/ap-south-1/wi-develop-eks-cluster/addons/aws-alb-controller.yaml
          #   namespace: kube-system

  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/devopsraj178-ops/tf-wi-aws.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - '../../{{valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
